name: Build and deploy JAR app to Azure Web App - GefMottu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write   
      contents: read    

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files (debug)
        run: ls -R

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GefMottu'
          slot-name: 'Production'
          package: 'gef-0.0.1-SNAPSHOT.jar'


