name: Build and deploy JAR app to Azure Web App - GefMottu

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: List built JAR (debug)
        run: ls -lh build/libs

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: 'build/libs/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app
          path: build/libs

      - name: Login to Azure
        uses: azure/login@v2
        with:
          auth-type: 'SERVICE_PRINCIPAL'
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Gef-Mottu-Dev-App'
          slot-name: 'production'
          package: 'build/libs/gef-0.0.1-SNAPSHOT.jar'
